export function exportPlainText(contributionTable) {
    console.log('[Export Utilities] generating plaintext representation of table');
    const longestCategory = contributionTable.rows.reduce((a,b) => {  return a.length > b.length ? a : b }).length;

    let rawFormat = '';
    rawFormat += '| ' + ' '.repeat(longestCategory) + ' | ' + contributionTable.cols.join(' | ') + ' |\n';
    rawFormat += '| ' + '-'.repeat(longestCategory-1) + ': | :' + contributionTable.cols.map(col => { return '-'.repeat(col.length-2)}).join(': | :') + ': |\n';
    for (const [i, row] of contributionTable.rows.entries()) {
        rawFormat += '| ' + row + ' '.repeat(longestCategory-row.length) + ' | ' + contributionTable.contributions.map((contribution, index) => {
            const colLength = contributionTable.cols[index].length;
            const contDegree = contribution[i]
            return ' '.repeat(Math.floor((colLength-contDegree)/2)) + '*'.repeat(contDegree) + ' '.repeat(Math.ceil((colLength-contDegree)/2));
        }).join(' | ') + ' |\n';
    }

    return rawFormat
}

// export in format pastable in LaTeX. Requires/includes xcolor package import
export function exportRichLatex(contributionTable) {
    const LUT = ['FFFFFF','A0A0A0','303030','000000'];
    const numcols = contributionTable.cols.length;
    console.log('[Export Utilities] generating rich LaTeX representation of table');
    let table = '';
    table += '% Contribution table generated by https://nemoandrea.github.io/better-contributions/editor \n';
    table += '% \\usepackage{array} \n'; // needed for fixed column widths
    table += '% \\usepackage[table]{xcolor} \n'; // needed for shaded cells
    table += '% \\usepackage{graphicx} \n'; // needed for rotated text
    table += '% \\usepackage{hhline} \n'; // needed for shaded cells
    table += '\\newcommand*\\rot{\\rotatebox{90}} \n';
    table += '\\setlength{\\arrayrulewidth}{0.7mm} \n'; // appearance
    table += '\\renewcommand{\\arraystretch}{2.1} \n';  // bit of a hacky way to get boxes to be close to square
    table += '\\begin{tabular}{ r | ' + 'm{0.5cm} | '.repeat(numcols) + '} \n';
    // the \multicolumn{1}{c}{} is a bit hacky, but it removes the vertical lines from the header
    table += '\\multicolumn{1}{c}{} & \\multicolumn{1}{c}{\\rot{' + contributionTable.cols.join('}} & \\multicolumn{1}{c}{\\rot{') + '}} \\\\ \n';
    table += '\\hhline{~|' + '-|'.repeat(numcols) +'} \n';
    for (const [i, row] of contributionTable.rows.entries() ) {
        table += row + ' & ' + contributionTable.contributions.map(contribution => {
            return '\\cellcolor[HTML]{' + LUT[contribution[i]] + '}';
        }).join(' & ') + ' \\\\ \n'
        table += '\\hhline{~|' + '-|'.repeat(numcols) +'} \n';
    }
    table += '\\end{tabular}';

    return table
}

// same as rich latex, but without any additional packages
export function exportBasicLatex(contributionTable) {
    console.log('[Export Utilities] generating basic LaTeX representation of table');
    const numcols = contributionTable.cols.length;

    let table = '';
    table += '% Contribution table (no-package mode) generated by https://nemoandrea.github.io/better-contributions/editor \n';
    table += '\\setlength{\\arrayrulewidth}{0.7mm} \n'; // appearance
    table += '\\renewcommand{\\arraystretch}{2.1} \n';  // bit of a hacky way to get boxes to have more square aspect
    table += '\\begin{tabular}{ r | ' + 'c | '.repeat(numcols) + '} \n';
    table += '\\multicolumn{1}{c}{} & \\multicolumn{1}{c}{' + contributionTable.cols.join('} & \\multicolumn{1}{c}{') + '} \\\\ \n';
    table += '\\cline{2-'+ (numcols+1) + '} \n';
    for (const [i, row] of contributionTable.rows.entries() ) {
        table += row + ' & ' + contributionTable.contributions.map(contribution => {
            return '*'.repeat(contribution[i]);
        }).join(' & ') + ' \\\\ \n';
        table += '\\cline{2-'+ (numcols+1) + '} \n';
    }
    table += '\\end{tabular}';

    return table
}
